export const verticalAxis = ["1", "2", "3", "4", "5", "6", "7", "8"];
export const horizontalAxis = ["a", "b", "c", "d", "e", "f", "g", "h"];

export const board = [
	{
		id: "0",
		name: "1a",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "1",
		name: "1b",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "2",
		name: "1c",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "3",
		name: "1d",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "4",
		name: "1e",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "5",
		name: "1f",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "6",
		name: "1g",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "7",
		name: "1h",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "8",
		name: "2a",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "9",
		name: "2b",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "10",
		name: "2c",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "11",
		name: "2d",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "12",
		name: "2e",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "13",
		name: "2f",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "14",
		name: "2g",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "15",
		name: "2h",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "16",
		name: "3a",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "17",
		name: "3b",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "18",
		name: "3c",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "19",
		name: "3d",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "20",
		name: "3e",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "21",
		name: "3f",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "22",
		name: "3g",
		className: "white-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "23",
		name: "3h",
		className: "black-tile",
		isFull: true,
		stoneColor: "white",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "24",
		name: "4a",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "25",
		name: "4b",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "26",
		name: "4c",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "27",
		name: "4d",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "28",
		name: "4e",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "29",
		name: "4f",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "30",
		name: "4g",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "31",
		name: "4h",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "32",
		name: "5a",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "33",
		name: "5b",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "34",
		name: "5c",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "35",
		name: "5d",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "36",
		name: "5e",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "37",
		name: "5f",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "38",
		name: "5g",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "39",
		name: "5h",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "40",
		name: "6a",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "41",
		name: "6b",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "42",
		name: "6c",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "43",
		name: "6d",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "44",
		name: "6e",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "45",
		name: "6f",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "46",
		name: "6g",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "47",
		name: "6h",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "48",
		name: "7a",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "49",
		name: "7b",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "50",
		name: "7c",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "51",
		name: "7d",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "52",
		name: "7e",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "53",
		name: "7f",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "54",
		name: "7g",
		className: "white-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "55",
		name: "7h",
		className: "black-tile",
		isFull: true,
		stoneColor: "black",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "56",
		name: "8a",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "57",
		name: "8b",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "58",
		name: "8c",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "59",
		name: "8d",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "60",
		name: "8e",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "61",
		name: "8f",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "62",
		name: "8g",
		className: "black-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
	{
		id: "63",
		name: "8h",
		className: "white-tile",
		isFull: false,
		stoneColor: "",
		isDama: false,
		isMovable: false,
		isSelected: false,
	},
];
